### ISSUE TITLE
requirements missing

### ISSUE THREAD

**Issue by tankz0r** [minerva-ml/open-solution-avito-demand-prediction#49]
Where can I find necessary requirements for the project?

**Comment by jakubczakon** [comment]
@tankz0r hi, I've just added the requirements. 
It should work fine now but I generated them with pipreqs so there could be something missing.

**Comment by tankz0r** [comment]
Thank you, I will try it. By the way, can you give some explanations or link to the resource where to read about the class ```Step```.

**Comment by jakubczakon** [comment]
@tankz0r done in https://github.com/minerva-ml/open-solution-avito-demand-prediction/commit/29f943b6d9fd7e9b2f6af7e16010b5c5d0350680
