### ISSUE TITLE
Text features - hand crafted features from toxic competition

### ISSUE THREAD

**Issue by jakubczakon** [minerva-ml/open-solution-avito-demand-prediction#6]
* Check features from `Toxic` competition and add them to this challenge.

**Comment by kamil-kaczmarek** [comment]
@Leoniak713 use this: https://github.com/minerva-ml/steps/blob/dev/steps/preprocessing/text.py

**Comment by kamil-kaczmarek** [comment]
Maybe *latinization* is necessary. (@Leoniak713 )
